# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


class ChaincodeEvent(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    chaincode_id = ... # type: typing___Text
    tx_id = ... # type: typing___Text
    event_name = ... # type: typing___Text
    payload = ... # type: bytes

    def __init__(self,
        *,
        chaincode_id : typing___Optional[typing___Text] = None,
        tx_id : typing___Optional[typing___Text] = None,
        event_name : typing___Optional[typing___Text] = None,
        payload : typing___Optional[bytes] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> ChaincodeEvent: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"chaincode_id",u"event_name",u"payload",u"tx_id"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"chaincode_id",b"chaincode_id",u"event_name",b"event_name",u"payload",b"payload",u"tx_id",b"tx_id"]) -> None: ...
