# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from google.protobuf.timestamp_pb2 import (
    Timestamp as google___protobuf___timestamp_pb2___Timestamp,
)

from typing import (
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


class ProposalResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    version = ... # type: int
    payload = ... # type: bytes

    @property
    def timestamp(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

    @property
    def response(self) -> Response: ...

    @property
    def endorsement(self) -> Endorsement: ...

    def __init__(self,
        *,
        version : typing___Optional[int] = None,
        timestamp : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
        response : typing___Optional[Response] = None,
        payload : typing___Optional[bytes] = None,
        endorsement : typing___Optional[Endorsement] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> ProposalResponse: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"endorsement",u"response",u"timestamp"]) -> bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"endorsement",u"payload",u"response",u"timestamp",u"version"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"endorsement",b"endorsement",u"response",b"response",u"timestamp",b"timestamp"]) -> bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"endorsement",b"endorsement",u"payload",b"payload",u"response",b"response",u"timestamp",b"timestamp",u"version",b"version"]) -> None: ...

class Response(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    status = ... # type: int
    message = ... # type: typing___Text
    payload = ... # type: bytes

    def __init__(self,
        *,
        status : typing___Optional[int] = None,
        message : typing___Optional[typing___Text] = None,
        payload : typing___Optional[bytes] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> Response: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"message",u"payload",u"status"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"message",b"message",u"payload",b"payload",u"status",b"status"]) -> None: ...

class ProposalResponsePayload(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    proposal_hash = ... # type: bytes
    extension = ... # type: bytes

    def __init__(self,
        *,
        proposal_hash : typing___Optional[bytes] = None,
        extension : typing___Optional[bytes] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> ProposalResponsePayload: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"extension",u"proposal_hash"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"extension",b"extension",u"proposal_hash",b"proposal_hash"]) -> None: ...

class Endorsement(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    endorser = ... # type: bytes
    signature = ... # type: bytes

    def __init__(self,
        *,
        endorser : typing___Optional[bytes] = None,
        signature : typing___Optional[bytes] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> Endorsement: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"endorser",u"signature"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"endorser",b"endorser",u"signature",b"signature"]) -> None: ...
