# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


class ChaincodeQueryResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def chaincodes(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[ChaincodeInfo]: ...

    def __init__(self,
        *,
        chaincodes : typing___Optional[typing___Iterable[ChaincodeInfo]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> ChaincodeQueryResponse: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"chaincodes"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"chaincodes",b"chaincodes"]) -> None: ...

class ChaincodeInfo(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    name = ... # type: typing___Text
    version = ... # type: typing___Text
    path = ... # type: typing___Text
    input = ... # type: typing___Text
    escc = ... # type: typing___Text
    vscc = ... # type: typing___Text
    id = ... # type: bytes

    def __init__(self,
        *,
        name : typing___Optional[typing___Text] = None,
        version : typing___Optional[typing___Text] = None,
        path : typing___Optional[typing___Text] = None,
        input : typing___Optional[typing___Text] = None,
        escc : typing___Optional[typing___Text] = None,
        vscc : typing___Optional[typing___Text] = None,
        id : typing___Optional[bytes] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> ChaincodeInfo: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"escc",u"id",u"input",u"name",u"path",u"version",u"vscc"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"escc",b"escc",u"id",b"id",u"input",b"input",u"name",b"name",u"path",b"path",u"version",b"version",u"vscc",b"vscc"]) -> None: ...

class ChannelQueryResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def channels(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[ChannelInfo]: ...

    def __init__(self,
        *,
        channels : typing___Optional[typing___Iterable[ChannelInfo]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> ChannelQueryResponse: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"channels"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"channels",b"channels"]) -> None: ...

class ChannelInfo(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    channel_id = ... # type: typing___Text

    def __init__(self,
        *,
        channel_id : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> ChannelInfo: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"channel_id"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"channel_id",b"channel_id"]) -> None: ...
