# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from snakeskin.protos.peer.proposal_response_pb2 import (
    Endorsement as snakeskin___protos___peer___proposal_response_pb2___Endorsement,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


class SignedChaincodeDeploymentSpec(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    chaincode_deployment_spec = ... # type: bytes
    instantiation_policy = ... # type: bytes

    @property
    def owner_endorsements(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[snakeskin___protos___peer___proposal_response_pb2___Endorsement]: ...

    def __init__(self,
        *,
        chaincode_deployment_spec : typing___Optional[bytes] = None,
        instantiation_policy : typing___Optional[bytes] = None,
        owner_endorsements : typing___Optional[typing___Iterable[snakeskin___protos___peer___proposal_response_pb2___Endorsement]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> SignedChaincodeDeploymentSpec: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"chaincode_deployment_spec",u"instantiation_policy",u"owner_endorsements"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"chaincode_deployment_spec",b"chaincode_deployment_spec",u"instantiation_policy",b"instantiation_policy",u"owner_endorsements",b"owner_endorsements"]) -> None: ...
