# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from snakeskin.protos.common.collection_pb2 import (
    CollectionConfigPackage as snakeskin___protos___common___collection_pb2___CollectionConfigPackage,
)

from snakeskin.protos.ledger.rwset.rwset_pb2 import (
    TxPvtReadWriteSet as snakeskin___protos___ledger___rwset___rwset_pb2___TxPvtReadWriteSet,
)

from typing import (
    Mapping as typing___Mapping,
    MutableMapping as typing___MutableMapping,
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


class TxPvtReadWriteSetWithConfigInfo(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class CollectionConfigsEntry(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        key = ... # type: typing___Text

        @property
        def value(self) -> snakeskin___protos___common___collection_pb2___CollectionConfigPackage: ...

        def __init__(self,
            *,
            key : typing___Optional[typing___Text] = None,
            value : typing___Optional[snakeskin___protos___common___collection_pb2___CollectionConfigPackage] = None,
            ) -> None: ...
        @classmethod
        def FromString(cls, s: bytes) -> TxPvtReadWriteSetWithConfigInfo.CollectionConfigsEntry: ...
        def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        if sys.version_info >= (3,):
            def HasField(self, field_name: typing_extensions___Literal[u"value"]) -> bool: ...
            def ClearField(self, field_name: typing_extensions___Literal[u"key",u"value"]) -> None: ...
        else:
            def HasField(self, field_name: typing_extensions___Literal[u"value",b"value"]) -> bool: ...
            def ClearField(self, field_name: typing_extensions___Literal[u"key",b"key",u"value",b"value"]) -> None: ...

    endorsed_at = ... # type: int

    @property
    def pvt_rwset(self) -> snakeskin___protos___ledger___rwset___rwset_pb2___TxPvtReadWriteSet: ...

    @property
    def collection_configs(self) -> typing___MutableMapping[typing___Text, snakeskin___protos___common___collection_pb2___CollectionConfigPackage]: ...

    def __init__(self,
        *,
        endorsed_at : typing___Optional[int] = None,
        pvt_rwset : typing___Optional[snakeskin___protos___ledger___rwset___rwset_pb2___TxPvtReadWriteSet] = None,
        collection_configs : typing___Optional[typing___Mapping[typing___Text, snakeskin___protos___common___collection_pb2___CollectionConfigPackage]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> TxPvtReadWriteSetWithConfigInfo: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"pvt_rwset"]) -> bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"collection_configs",u"endorsed_at",u"pvt_rwset"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"pvt_rwset",b"pvt_rwset"]) -> bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"collection_configs",b"collection_configs",u"endorsed_at",b"endorsed_at",u"pvt_rwset",b"pvt_rwset"]) -> None: ...
