# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


class SerializedIdentity(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    mspid = ... # type: typing___Text
    id_bytes = ... # type: bytes

    def __init__(self,
        *,
        mspid : typing___Optional[typing___Text] = None,
        id_bytes : typing___Optional[bytes] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> SerializedIdentity: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"id_bytes",u"mspid"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"id_bytes",b"id_bytes",u"mspid",b"mspid"]) -> None: ...

class SerializedIdemixIdentity(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    nym_x = ... # type: bytes
    nym_y = ... # type: bytes
    ou = ... # type: bytes
    role = ... # type: bytes
    proof = ... # type: bytes

    def __init__(self,
        *,
        nym_x : typing___Optional[bytes] = None,
        nym_y : typing___Optional[bytes] = None,
        ou : typing___Optional[bytes] = None,
        role : typing___Optional[bytes] = None,
        proof : typing___Optional[bytes] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> SerializedIdemixIdentity: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"nym_x",u"nym_y",u"ou",u"proof",u"role"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"nym_x",b"nym_x",u"nym_y",b"nym_y",u"ou",b"ou",u"proof",b"proof",u"role",b"role"]) -> None: ...
