# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: snakeskin/protos/orderer/etcdraft/configuration.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='snakeskin/protos/orderer/etcdraft/configuration.proto',
  package='etcdraft',
  syntax='proto3',
  serialized_options=_b('\n.org.hyperledger.fabric.protos.orderer.etcdraftZ5github.com/hyperledger/fabric/protos/orderer/etcdraft'),
  serialized_pb=_b('\n5snakeskin/protos/orderer/etcdraft/configuration.proto\x12\x08\x65tcdraft\"W\n\x08Metadata\x12\'\n\nconsenters\x18\x01 \x03(\x0b\x32\x13.etcdraft.Consenter\x12\"\n\x07options\x18\x02 \x01(\x0b\x32\x11.etcdraft.Options\"Y\n\tConsenter\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\r\x12\x17\n\x0f\x63lient_tls_cert\x18\x03 \x01(\x0c\x12\x17\n\x0fserver_tls_cert\x18\x04 \x01(\x0c\"\x9f\x01\n\x07Options\x12\x15\n\rtick_interval\x18\x01 \x01(\x04\x12\x15\n\relection_tick\x18\x02 \x01(\r\x12\x16\n\x0eheartbeat_tick\x18\x03 \x01(\r\x12\x19\n\x11max_inflight_msgs\x18\x04 \x01(\r\x12\x18\n\x10max_size_per_msg\x18\x05 \x01(\x04\x12\x19\n\x11snapshot_interval\x18\x06 \x01(\x04\"\xdd\x01\n\x0cRaftMetadata\x12:\n\nconsenters\x18\x01 \x03(\x0b\x32&.etcdraft.RaftMetadata.ConsentersEntry\x12\x19\n\x11next_consenter_id\x18\x02 \x01(\x04\x12\x1a\n\x12\x63onf_change_counts\x18\x03 \x01(\x04\x12\x12\n\nraft_index\x18\x04 \x01(\x04\x1a\x46\n\x0f\x43onsentersEntry\x12\x0b\n\x03key\x18\x01 \x01(\x04\x12\"\n\x05value\x18\x02 \x01(\x0b\x32\x13.etcdraft.Consenter:\x02\x38\x01\x42g\n.org.hyperledger.fabric.protos.orderer.etcdraftZ5github.com/hyperledger/fabric/protos/orderer/etcdraftb\x06proto3')
)




_METADATA = _descriptor.Descriptor(
  name='Metadata',
  full_name='etcdraft.Metadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='consenters', full_name='etcdraft.Metadata.consenters', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='options', full_name='etcdraft.Metadata.options', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=154,
)


_CONSENTER = _descriptor.Descriptor(
  name='Consenter',
  full_name='etcdraft.Consenter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='host', full_name='etcdraft.Consenter.host', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='etcdraft.Consenter.port', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client_tls_cert', full_name='etcdraft.Consenter.client_tls_cert', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='server_tls_cert', full_name='etcdraft.Consenter.server_tls_cert', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=245,
)


_OPTIONS = _descriptor.Descriptor(
  name='Options',
  full_name='etcdraft.Options',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tick_interval', full_name='etcdraft.Options.tick_interval', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='election_tick', full_name='etcdraft.Options.election_tick', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='heartbeat_tick', full_name='etcdraft.Options.heartbeat_tick', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_inflight_msgs', full_name='etcdraft.Options.max_inflight_msgs', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_size_per_msg', full_name='etcdraft.Options.max_size_per_msg', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='snapshot_interval', full_name='etcdraft.Options.snapshot_interval', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=407,
)


_RAFTMETADATA_CONSENTERSENTRY = _descriptor.Descriptor(
  name='ConsentersEntry',
  full_name='etcdraft.RaftMetadata.ConsentersEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='etcdraft.RaftMetadata.ConsentersEntry.key', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='etcdraft.RaftMetadata.ConsentersEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=561,
  serialized_end=631,
)

_RAFTMETADATA = _descriptor.Descriptor(
  name='RaftMetadata',
  full_name='etcdraft.RaftMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='consenters', full_name='etcdraft.RaftMetadata.consenters', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='next_consenter_id', full_name='etcdraft.RaftMetadata.next_consenter_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='conf_change_counts', full_name='etcdraft.RaftMetadata.conf_change_counts', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='raft_index', full_name='etcdraft.RaftMetadata.raft_index', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_RAFTMETADATA_CONSENTERSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=410,
  serialized_end=631,
)

_METADATA.fields_by_name['consenters'].message_type = _CONSENTER
_METADATA.fields_by_name['options'].message_type = _OPTIONS
_RAFTMETADATA_CONSENTERSENTRY.fields_by_name['value'].message_type = _CONSENTER
_RAFTMETADATA_CONSENTERSENTRY.containing_type = _RAFTMETADATA
_RAFTMETADATA.fields_by_name['consenters'].message_type = _RAFTMETADATA_CONSENTERSENTRY
DESCRIPTOR.message_types_by_name['Metadata'] = _METADATA
DESCRIPTOR.message_types_by_name['Consenter'] = _CONSENTER
DESCRIPTOR.message_types_by_name['Options'] = _OPTIONS
DESCRIPTOR.message_types_by_name['RaftMetadata'] = _RAFTMETADATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Metadata = _reflection.GeneratedProtocolMessageType('Metadata', (_message.Message,), {
  'DESCRIPTOR' : _METADATA,
  '__module__' : 'snakeskin.protos.orderer.etcdraft.configuration_pb2'
  # @@protoc_insertion_point(class_scope:etcdraft.Metadata)
  })
_sym_db.RegisterMessage(Metadata)

Consenter = _reflection.GeneratedProtocolMessageType('Consenter', (_message.Message,), {
  'DESCRIPTOR' : _CONSENTER,
  '__module__' : 'snakeskin.protos.orderer.etcdraft.configuration_pb2'
  # @@protoc_insertion_point(class_scope:etcdraft.Consenter)
  })
_sym_db.RegisterMessage(Consenter)

Options = _reflection.GeneratedProtocolMessageType('Options', (_message.Message,), {
  'DESCRIPTOR' : _OPTIONS,
  '__module__' : 'snakeskin.protos.orderer.etcdraft.configuration_pb2'
  # @@protoc_insertion_point(class_scope:etcdraft.Options)
  })
_sym_db.RegisterMessage(Options)

RaftMetadata = _reflection.GeneratedProtocolMessageType('RaftMetadata', (_message.Message,), {

  'ConsentersEntry' : _reflection.GeneratedProtocolMessageType('ConsentersEntry', (_message.Message,), {
    'DESCRIPTOR' : _RAFTMETADATA_CONSENTERSENTRY,
    '__module__' : 'snakeskin.protos.orderer.etcdraft.configuration_pb2'
    # @@protoc_insertion_point(class_scope:etcdraft.RaftMetadata.ConsentersEntry)
    })
  ,
  'DESCRIPTOR' : _RAFTMETADATA,
  '__module__' : 'snakeskin.protos.orderer.etcdraft.configuration_pb2'
  # @@protoc_insertion_point(class_scope:etcdraft.RaftMetadata)
  })
_sym_db.RegisterMessage(RaftMetadata)
_sym_db.RegisterMessage(RaftMetadata.ConsentersEntry)


DESCRIPTOR._options = None
_RAFTMETADATA_CONSENTERSENTRY._options = None
# @@protoc_insertion_point(module_scope)
